extraction:
  cpp:
    after_prepare: 
      - python report.py 105
  cobol:
    after_prepare: 
      - python report.py 105
  csharp:
    after_prepare: 
      - python report.py 105
  java:
    after_prepare: 
      - python report.py 105
  javascript:
    after_prepare: 
      - python report.py 105
  python:
    after_prepare: 
      - python report.py 105
